FROM python:3.11-slim

WORKDIR /app

# Instalar apenas streamlit e requests
RUN pip install --upgrade pip && \
    pip cache purge && \
    pip install --no-cache-dir streamlit requests httpx selectolax pydantic

# Copiar o código do Streamlit e crawler
COPY streamlit/ ./streamlit/
COPY crawler/ ./crawler/

# Expor porta
EXPOSE 8501

# Comando simples
CMD ["streamlit", "run", "streamlit/view.py", "--server.port", "8501", "--server.address", "0.0.0.0"]