FROM python:3.11-slim

WORKDIR /app

RUN pip install --upgrade pip && \
    pip cache purge && \
    pip install --no-cache-dir streamlit requests httpx selectolax pydantic

COPY streamlit/ ./streamlit/
COPY crawler/ ./crawler/

EXPOSE 8501

CMD ["streamlit", "run", "streamlit/view.py", "--server.port", "8501", "--server.address", "0.0.0.0"]