version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: articles_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: articles_db
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/articles_db --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: articles_fastapi
    restart: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - ./chroma_db:/app/chroma_db
      - .:/app
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - MONGO_HOST=mongodb

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
